#- hosts: localhost
#  gather_facts: false
#  vars:
#    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
#    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
#    TOWER_GUID: "{{ lookup('env','TOWER_GUID') }}"
#  tasks:
#  - name: Create In-memory Inventory
#    add_host: 
#      name: workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}
#      group: workstation
#      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
#      ansible_ssh_user: cloud-user



- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-aws, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
#    - {name: db-tier, tags: [dbs, postgres]}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}
