- hosts: localhost
  gather_facts: false
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    TOWER_GUID: "{{ lookup('env','TOWER_GUID') }}"
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}
      group: workstation
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
 
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: 'frontend'
    register: openstack_info
  
#  - name: Check if all osp instance exist
#    debug: "{{ openstack_info.openstack_servers | length }}"
#    register: osp_instance

  - debug: var=openstack_info

