---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
     register: result
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_hostname: "{{ item.name }}"
     with_items: "{{result.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      ansible_hostname: "{{ item.name }}"
     with_items: "{{result.openstack_servers}}"
#     with_items: "{{result.ansible_facts.openstack_servers}}"
